pull_request_rules:
  - name: automatic merge when GitHub branch protection passes (others)
    conditions:
      - base=main
      - -author~=^dependabot(|-preview)\[bot\]$
      - 'label=:shipit: merge'
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: automatic merge when GitHub branch protection passes
    conditions:
      - merged
      - 'label=:shipit: merge'
    actions:
      label:
        remove:
          - ':shipit: merge'
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      label:
        remove:
          - ':shipit: merge'
      delete_head_branch: {}
