name: Create Milestone and Draft Release

on:
  workflow_call:
    # inputs:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '0 0 * * 4'

jobs:
  create_milestone_and_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Fetch all history for all tags and branches
        run: git fetch --prune

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v0.9.11
        with:
          versionSpec: '0.11.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11

      - name: Create Milestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: v${{ steps.gitversion.outputs.majorMinorPatch }}
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        continue-on-error: true

      - name: sync milestones
        uses: RocketSurgeonsGuild/actions/sync-milestone@v0.2.6
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ github.token }}

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          draft: true
          omitNameDuringUpdate: true
          name: "v${{ steps.gitversion.outputs.majorMinorPatch }}"
          tag: "v${{ steps.gitversion.outputs.majorMinorPatch }}"
          token: ${{ github.token }}
          commit: ${{ github.base_ref }}
